name: CI/CD Pipeline (Docker Hub + Azure Web App)

on:
  push:

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

  build-and-push:
    name: Build and Push Docker to Docker Hub
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: komendra
          password: komu1004@

      - name: Build Docker Image
        run: |
          docker build -t komendra/creditcard:latest .

      - name: Push Docker Image
        run: |
          docker push komendra/creditcard:latest
